### ISSUE TITLE
Add file path to the IDE section

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/iLoveLAMP#1]
The filename is displayed in the input box when editing the files, it would be cool if the entire file path is displayed when editing files from a remote host. The path should go next to the input box, or on top of it, not in the input itself.

**Comment by Mknsri** [comment]
Can I grab this?

**Comment by Pamblam** [comment]
Yes sir, please do

**Comment by Mknsri** [comment]
PR #4

**Comment by pranjaljn97** [comment]
Is it Done? I wanna grab this
